### PR TITLE
Feature/ng 12

### LINKED ISSUE #12: Update dependencies and peer dependencies
#### Describe the desired behavior
Check the current/latest version of all dependencies and peer dependencies. Update the package.json to include the latest.

#### Describe the current behavior
Using old versions of dependencies.

#### Is this request related to a current issue?
The newest version of NPM fails on npm install when there are peer dependency issues. 

#### Additional Context
After updating the versions of dependencies, make sure that things still work as expected.

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #12 

#### Changes proposed in this Pull Request:
- Update to use ng 12 dependencies
- Update to use v6.0.0 of pxb ng comp lib & v6.3.0 of pxb ng themes.

### CODE REVIEW

**Review by joebochill — APPROVED** [review]

**Comment by emclaug2** [comment]
This can go straight to master after this is merged in.

**Comment by emclaug2** [comment]
Tomorrow ^

**Comment by joebochill** [comment]
> This can go straight to master after this is merged in.

Can it go to master if the currently latest version of the CLI is pumping out angular 11 projects? Or do we need to wait?

**Review by daileytj — APPROVED** [review]

**Comment by daileytj** [comment]
@emclaug2 you have your code owner approval now 😃

**Comment by emclaug2** [comment]
> Can it go to master if the currently latest version of the CLI is pumping out angular 11 projects? Or do we need to wait?

This can go in immediately; I just tested v6.0.0 in an angular 11 project & there's no issues.  I was expecting a missing peer dependency warning, but then realized there's no required angular version specified in our peer deps.  This should be added in as a patch, I'll make an issue.  Seems this was dropped (for some reason, probably accidently) in v5.0.0.

**Pull request merged**
