### PR TITLE
Add publish step to ci

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Add deploy step in ci config for master branch

### CODE REVIEW

**Comment by emclaug2** [comment]
Not sure how to test this stuff out given that it only runs when we merge into master; Joe and I tested this stuff during office hours. 

Only thing that changed was the command used to fetch local package version info; this change was tested in my own repo's circleci found here: https://app.circleci.com/pipelines/github/emclaug2/angular-cli-templates/15/workflows/b87eb5d9-b5d6-45fa-9de9-891eb78080cf/jobs/22

**Comment by emclaug2** [comment]
Screen Shot 2021-01-12 at 3 07 35 PM

**Comment by emclaug2** [comment]
NPM access token has been added to env variables in circle ci.

**Review by joebochill — APPROVED** [review]

**Comment by joebochill** [comment]
Looks good. We can pull in the stories to polish up the templates next sprint and see how it works.

**Pull request merged**
